### ISSUE TITLE
"Wrong version of PyObjC C API (got 21, expected 20)"

### ISSUE THREAD

**Issue by dbieber** [ActivityWatch/aw-watcher-input#2]
I just installed aw-watcher-input with poetry.
When I run `aw-watcher-input --help` I get `RuntimeError: Wrong version of PyObjC C API (got 21, expected 20)`.

What would be required to update aw-watcher-input to work with version 21?

Here's the full stacktrace:

```
Traceback (most recent call last):
  File "/Users/dbieber/.virtualenvs/aw/bin/aw-watcher-input", line 2, in <module>
    from aw_watcher_input.main import main
  File "/Users/dbieber/code/github/ActivityWatch/aw-watcher-input/src/aw_watcher_input/__init__.py", line 1, in <module>
    from . import main
  File "/Users/dbieber/code/github/ActivityWatch/aw-watcher-input/src/aw_watcher_input/main.py", line 9, in <module>
    from aw_watcher_afk.listeners import KeyboardListener, MouseListener
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/aw_watcher_afk/__init__.py", line 1, in <module>
    from . import __main__
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/aw_watcher_afk/__main__.py", line 5, in <module>
    from aw_watcher_afk.afk import AFKWatcher
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/aw_watcher_afk/afk.py", line 17, in <module>
    from .macos import seconds_since_last_input
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/aw_watcher_afk/macos.py", line 2, in <module>
    from Quartz.CoreGraphics import (CGEventSourceSecondsSinceLastEventType,
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/Quartz/__init__.py", line 102, in <module>
    _load()
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/Quartz/__init__.py", line 28, in _load
    from Quartz import CoreGraphics as m
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/Quartz/CoreGraphics/__init__.py", line 143, in <module>
    _load(mod)
  File "/Users/dbieber/.virtualenvs/aw/lib/python3.7/site-packages/Quartz/CoreGraphics/__init__.py", line 51, in _load
    import Quartz.CoreGraphics._callbacks as m
RuntimeError: Wrong version of PyObjC C API (got 21, expected 20)
```

**Comment by ErikBjare** [comment]
This issue seems to originate in aw-watcher-afk (which depends on pyobjc). It's been breaking the CI for aw-watcher-afk for some time now, hopefully all that's needed is to update pyobjc.

If [this CI run](https://github.com/ActivityWatch/aw-watcher-afk/runs/1618459487) passes, then I've fixed it, and I'll update aw-watcher-input in just a moment :)

**Comment by ErikBjare** [comment]
aw-watcher-afk CI run passed! Fixed for aw-watcher-input in https://github.com/ActivityWatch/aw-watcher-input/commit/a6730e2fc9fc4cdd4ff304b5e1f7bf97ccbd33ae

Thanks for reporting :slightly_smiling_face:

**Comment by dbieber** [comment]
Thanks for your impressively prompt turn around fixing this! 🙏

**Comment by ErikBjare** [comment]
@dbieber You're just lucky, I was just about to stop working for the day :wink:

**Comment by dbieber** [comment]
Hmm, even after updating to a6730e2fc9fc4cdd4ff304b5e1f7bf97ccbd33ae I still get the same error. 

```
> pip freeze | grep aw
aw-client @ file:///Users/dbieber/.virtualenvs/aw/src/aw-client
aw-core @ file:///Users/dbieber/.virtualenvs/aw/src/aw-core
aw-qt==0.1.0
aw-server==0.9
aw-watcher-afk @ file:///Users/dbieber/.virtualenvs/aw/src/aw-watcher-afk
aw-watcher-input==0.1.0
aw-watcher-window==0.2.0
timeslot @ file:///Users/dbieber/.virtualenvs/aw/src/timeslot
```

**Comment by ErikBjare** [comment]
@dbieber Can you give me `pip freeze | grep pyobjc`? Did you run `poetry install` again?

If you have the latest pyobjc, it should work (otherwise I'm clueless).

**Comment by dbieber** [comment]
Installing in a fresh virtualenv resolved the issue,

now it starts but with these errors:

```
> aw-watcher-input 
INFO:aw_watcher_input.main:Starting watcher...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/dbieber/.virtualenvs/aw-watcher-input/lib/python3.7/site-packages/pykeyboard/mac.py", line 215, in run
    loopsource = Quartz.CFMachPortCreateRunLoopSource(None, tap, 0)
  File "/Users/dbieber/.virtualenvs/aw-watcher-input/lib/python3.7/site-packages/objc/_lazyimport.py", line 207, in __getattr__
    raise AttributeError(name)
AttributeError: CFMachPortCreateRunLoopSource

INFO:aw_watcher_input.main:No new input
INFO:aw_watcher_input.main:No new input
INFO:aw_watcher_input.main:No new input
INFO:aw_watcher_input.main:No new input
```

---

From the "working" virtualenv, here's the output of the requested command:
```
> pip freeze | grep pyobjc
pyobjc-core @ file:///Users/dbieber/Library/Caches/pypoetry/artifacts/b2/19/4f/005efdc28d19ef087a5e3b3785852305ba8d5d46460f72b9b271c65031/pyobjc_core-7.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
pyobjc-framework-Cocoa @ file:///Users/dbieber/Library/Caches/pypoetry/artifacts/e3/5b/6b/dd2dd93f4f528accbd314034720928c813b88865856ada4833032ba147/pyobjc_framework_Cocoa-7.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
pyobjc-framework-Quartz @ file:///Users/dbieber/Library/Caches/pypoetry/artifacts/75/a2/a2/96a923d37185a4a47deec56474de67a9edefcc98673e5d12467d40d038/pyobjc_framework_Quartz-7.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
```
And yes I did poetry install again.

**Comment by ErikBjare** [comment]
Huh, that's new. Might be caused by bumping pyobjc to 7.0. It presumably affects aw-watcher-afk as well.

**Comment by ErikBjare** [comment]
@dbieber I've opened an issue in the PyUserInput repo https://github.com/PyUserInput/PyUserInput/issues/61. It looks like an easy fix, but I might be wrong about that. 

If you have the time, feel free to give it a shot. Otherwise, I might look into it myself in a few weeks.

**Comment by dbieber** [comment]
Thanks for looking input it. I’ll let you know if I get a chance to look into it myself before then.

**Comment by dbieber** [comment]
I logged my progress in https://github.com/PyUserInput/PyUserInput/issues/61.
Ultimately switching to Python 3.9 (not sure if necessary) and rolling `jedi` back to version 0.17.2 resolved the issue.
No changes were needed to aw-watcher-input or PyUserInput.
